#!/bin/bash
# TCP Research Consortium - Research Progress Monitor
# Tracks file changes across all researcher workspaces

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MONITOR_LOG="$PROJECT_ROOT/consortium/research-activity.log"
CHANGES_DIR="$PROJECT_ROOT/consortium/change-summaries"

# Create monitoring infrastructure
mkdir -p "$CHANGES_DIR"
mkdir -p "$(dirname "$MONITOR_LOG")"

echo "📊 TCP Research Consortium - Change Monitor"
echo "=========================================="
echo "⏰ Monitor Time: $(date)"
echo "📁 Project Root: $PROJECT_ROOT"
echo "📝 Activity Log: $MONITOR_LOG"

# Function to get file change summary
get_file_summary() {
    local file="$1"
    local researcher="$2"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    
    if [[ -f "$file" ]]; then
        local size=$(wc -l < "$file" 2>/dev/null || echo "0")
        local last_modified=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M:%S" "$file" 2>/dev/null || echo "Unknown")
        
        echo "[$timestamp] $researcher: $(basename "$file") - $size lines (modified: $last_modified)" >> "$MONITOR_LOG"
        
        # Create detailed change summary
        local summary_file="$CHANGES_DIR/${researcher}_$(basename "$file")_summary.md"
        cat > "$summary_file" << EOF
# $(basename "$file") - $researcher

**Last Modified**: $last_modified
**Size**: $size lines
**Location**: $file

## Recent Activity
- File updated at $last_modified
- Current size: $size lines

## File Preview (first 20 lines)
\`\`\`
$(head -n 20 "$file" 2>/dev/null || echo "Cannot read file")
\`\`\`

## File Preview (last 10 lines)
\`\`\`
$(tail -n 10 "$file" 2>/dev/null || echo "Cannot read file")
\`\`\`
EOF
    fi
}

# Monitor each researcher's workspace
RESEARCHERS=("elena-vasquez" "marcus-chen" "yuki-tanaka" "aria-blackwood" "sam-mitchell")

echo -e "\n🔍 Scanning researcher workspaces for changes..."

for researcher in "${RESEARCHERS[@]}"; do
    workspace="$PROJECT_ROOT/consortium/$researcher"
    
    if [[ -d "$workspace" ]]; then
        echo "📂 Scanning $researcher workspace..."
        
        # Find all files modified in last 24 hours
        recent_files=$(find "$workspace" -type f -mtime -1 2>/dev/null || true)
        
        if [[ -n "$recent_files" ]]; then
            echo "   ✅ Found recent activity for $researcher"
            
            while IFS= read -r file; do
                if [[ -n "$file" ]]; then
                    get_file_summary "$file" "$researcher"
                    echo "      • $(basename "$file")"
                fi
            done <<< "$recent_files"
        else
            echo "   💤 No recent activity for $researcher"
        fi
    else
        echo "   ❌ Workspace not found: $workspace"
    fi
done

# Check for git changes in researcher branches
echo -e "\n🌿 Checking git branch activity..."
cd "$PROJECT_ROOT"

recent_branches=$(git for-each-ref --format='%(refname:short) %(committerdate)' refs/heads/ | grep -E "(research/|collaborative/)" | sort -k2 -r | head -10 || true)

if [[ -n "$recent_branches" ]]; then
    echo "Recent research branches:"
    echo "$recent_branches" | while read -r branch_info; do
        branch=$(echo "$branch_info" | awk '{print $1}')
        echo "   🌿 $branch"
        
        # Get recent commits on this branch
        recent_commits=$(git log --oneline --since="24 hours ago" "$branch" 2>/dev/null | head -5 || true)
        if [[ -n "$recent_commits" ]]; then
            echo "$recent_commits" | while read -r commit; do
                echo "      • $commit"
            done
        fi
    done
fi

# Generate research progress summary
echo -e "\n📊 Generating research progress summary..."

summary_file="$CHANGES_DIR/research_progress_$(date +%Y%m%d_%H%M%S).md"
cat > "$summary_file" << EOF
# TCP Research Consortium - Progress Summary

**Generated**: $(date)
**Monitor Run**: Research Change Detection

## Research Activity Overview

$(echo "### Active Researchers")
$(for researcher in "${RESEARCHERS[@]}"; do
    workspace="$PROJECT_ROOT/consortium/$researcher"
    if [[ -d "$workspace" ]]; then
        file_count=$(find "$workspace" -type f | wc -l)
        recent_count=$(find "$workspace" -type f -mtime -1 2>/dev/null | wc -l || echo "0")
        echo "- **$researcher**: $file_count total files, $recent_count recently modified"
    fi
done)

## Recent File Changes
$(tail -n 20 "$MONITOR_LOG" 2>/dev/null || echo "No recent activity logged")

## Git Branch Activity
$(echo "$recent_branches" | head -5)

## Change Summaries Available
$(ls -1 "$CHANGES_DIR"/*_summary.md 2>/dev/null | sed 's/.*\//- /' || echo "No summaries generated yet")

---
*Generated by TCP Research Consortium Change Monitor*
EOF

echo "✅ Progress summary saved: $summary_file"

# Output recent activity to console
echo -e "\n📈 Recent Research Activity Summary:"
echo "=================================="

if [[ -f "$MONITOR_LOG" ]]; then
    echo "Last 10 activities:"
    tail -n 10 "$MONITOR_LOG" 2>/dev/null || echo "No activity logged yet"
else
    echo "No activity log found - this may be the first run"
fi

echo -e "\n💡 Monitor Usage:"
echo "• Run this script regularly to track researcher progress"
echo "• Check $CHANGES_DIR for detailed file summaries"
echo "• Review $MONITOR_LOG for activity timeline"
echo "• Use research_progress_*.md files for status updates"

echo -e "\n✅ Research monitoring complete!"